### ISSUE TITLE
Async requests waving

### ISSUE THREAD

**Issue by nullswan** [dolevf/graphw00f#19]
- Prevent sending same requests twice
- Send requests asynchronously 

All of this will speedup by a lot the search.

**Comment by dolevf** [comment]
A bit of a nit question:

1. Is it really that slow that it requires async calls? in most of my previous engagements the fingerprinting took less than a second.
2. I don't see a whole lot of duplications when it comes to the fingerprinting requests, where do you see room for significant optimization?
