### ISSUE TITLE
Add HTTP header CLI option

### ISSUE THREAD

**Issue by noraj** [dolevf/graphw00f#26]
It would be nice to have a `-H, --header` CLI option to be able to arbitrary add HHTP headers to the request like cookie or authorization headers. I know it was asked for in #8 and the current workaround is to edit [config.py](https://github.com/dolevf/graphw00f/blob/main/conf.py) but that's not very handy for many reasons.

**Comment by dolevf** [comment]
This was added in 1.1.10. Thanks!
