### ISSUE TITLE
False negative detection when extensions keyword is present in errors response

### ISSUE THREAD

**Issue by D-Ace0** [dolevf/graphw00f#39]
When the GraphQL endpoint returns an error response containing the `extensions` keyword within the `errors` array, the `check` method in lib.py does not correctly detect this as a valid GraphQL endpoint.
![image](https://github.com/dolevf/graphw00f/assets/139914305/d61bc763-c8eb-4a58-b9eb-7e6eeee28cb1)

### Steps to Reproduce
1. Configure Graphw00f to query a GraphQL endpoint with introspection disabled.
2. Observe the response containing:
```json
{
    "errors": [
        {
            "message": "Introspection query is disabled for internal clients",
            "extensions": {
                "classification": "ExecutionAborted"
            }
        }
    ]
}
```

The issue was resolved by modifying this part of the check function in the following way:
```python
if response.get('data'):
    if response.get('data', {}).get('__typename', '') in ('Query', 'QueryRoot', 'query_root'):
        return True
elif response.get('errors') and (any('locations' in i for i in response['errors']) or any('extensions' in i for i in response['errors'])):
    return True
elif response.get('data'):
    return True
else:
    raise GraphQLDetectionFailed
```

This ensures that the presence of the extensions keyword within the errors array is correctly handled.

After:-
![image](https://github.com/dolevf/graphw00f/assets/139914305/761396b4-7bfe-41a1-a62d-783b66413ff1)

**Comment by dolevf** [comment]
Hello! would you like to open a PR on this?

**Comment by D-Ace0** [comment]
Hello. I did the PR
