### ISSUE TITLE
Headers are set empty before using them

### ISSUE THREAD

**Issue by azuax** [dolevf/graphw00f#44]
In main.py, line 90, only the parameters passed to the script for headers value are considered
https://github.com/dolevf/graphw00f/blob/701e4c16262481f9a7094a4b142f435a961497f5/main.py#L90

This leads the script to ignore the values passed in file `conf.py` in `HEADERS` variable.

**Comment by azuax** [comment]
Proposed solution, iterate through `conf.HEADERS` after line 89.
```python
for header in options.header:
    key, value = header.split(": ")
    headers[key] = value
for header in conf.HEADERS:
    headers[header] = conf.HEADERS[header]
```

**Comment by dolevf** [comment]
Would you like to open a PR with this fix?
