### ISSUE TITLE
POST request to fingerprint 

### ISSUE THREAD

**Issue by sm-xiaoK** [dolevf/graphw00f#47]
I have a graphql endpoint I can manually send introspection queries to, and I created a custom wordlist for the tool to use to access it, but it returns the error:

`[x] Could not find GraphQL anywhere.`

Could this be because the GraphQL endpoint needs to be requested via a POST request? A GET request to the endpoint returns a 403.

I could not see anywhere in the documentation to specify a different type of request method and I'm not versed enough to figure out in the code whether or not the tool is attempting a POST request to fingerprint. 

Thanks!

**Comment by dolevf** [comment]
Hi @sm-xiaoK,
graphw00f does use POST requests for detection. If it's a public endpoint, you can share the URL and I can investigate.

**Comment by sm-xiaoK** [comment]
I forgot to include the API token as a header. It works as expected now, thank you.
