### ISSUE TITLE
ariadne and strawberry have conflicting signatures

### ISSUE THREAD

**Issue by MdotTIM** [dolevf/graphw00f#6]
While testing on an Ariadne engine sending `query @deprecated {__typename}` returned `Directive '@deprecated' may not be used on query.` which is the signature for strawberry.

**Comment by dolevf** [comment]
Have you identified another possible way to fingerprint it? Otherwise I'll take a look :)

**Comment by dolevf** [comment]
Interesting @MdotTIM . I tested two implementations, one being Strawberry and the other one was Ariadne. Here is what I did:

1. Commented out Ariadne signature
2. Tested Ariadne endpoint
3. graphw00f returns no result

Then I did the same with Strawberry where I commented out Strawberry signature and it yielded no results.
 
TL;DR I couldn't get to a conflicting state. Is there an application or endpoint you can provide that I can test against?

**Comment by MdotTIM** [comment]
It was my bad, while verifying the signatures, I overlooked the second condition of strawberry, everything is working fine. thank you,
