### ISSUE TITLE
Feature: custom authorization header

### ISSUE THREAD

**Issue by Trobyss** [dolevf/graphw00f#8]
Hi !

Great project ! 
Is it possible (or is it planned) to add a custom header? I have a graphql app with an secure auth and I would need to add an authorization header in the request. Is it possible ?

Thanks ! 
Trobyss'

edit: I just find the `conf.py` :) it would be cool if it was specified in the readme

**Comment by dolevf** [comment]
hi there,

Yeah, some documentation on it wouldn't hurt. Perhaps you want to open a PR for this?

**Comment by dolevf** [comment]
https://github.com/dolevf/graphw00f/commit/6b70c307a1d8e33a35ab5af2cc5cad2bb226e36d
